server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml     #mapper文件路径
  type-aliases-package: cn.itcast.mybatis.generator.model,cn.itcast.mybatis.generator.vo   #实体类的包路径
  configuration:
    map-underscore-to-camel-case: true
